configuration-set.api-demo.profiles=
configuration-set.api-demo.suites=rest_api
configuration-set.api-demo.environments=demo

configuration-set.web-demo.profiles=web/headless/chrome
configuration-set.web-demo.suites=web_app
configuration-set.web-demo.environments=demo

# Visual
variables.visual.action=COMPARE_AGAINST
ui.visual.acceptable-diff-percentage=1.0
ui.visual.override-baselines=true
ui.visual.baseline-storage.filesystem.folder=#{T(java.lang.System).getProperty('user.dir')}/baseline
